Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
March 12, 2023 - 13:06:13
Django version 4.1.7, using settings 'django_pkms.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
March 12, 2023 - 13:06:15
Django version 4.1.7, using settings 'django_pkms.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.
Session data corrupted
[12/Mar/2023 13:06:36] "GET / HTTP/1.1" 302 0
Session data corrupted
[12/Mar/2023 13:06:36] "GET /accounts/login/?next=/ HTTP/1.1" 200 2439
/home/aegis/Code/django_pkms/django_pkms/settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
March 12, 2023 - 13:09:02
Django version 4.1.7, using settings 'django_pkms.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/aegis/Code/django_pkms/django_pkms/settings.py changed, reloading.
Traceback (most recent call last):
  File "/home/aegis/Code/django_pkms/manage.py", line 22, in <module>
    main()
  File "/home/aegis/Code/django_pkms/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/aegis/Code/django_pkms/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/aegis/Code/django_pkms/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/home/aegis/Code/django_pkms/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/home/aegis/Code/django_pkms/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aegis/Code/django_pkms/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/aegis/Code/django_pkms/django_pkms/settings.py", line 82, in <module>
    conn_str = os.environ['AZURE_POSTGRESQL_CONNECTIONSTRING']
               ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'AZURE_POSTGRESQL_CONNECTIONSTRING'
